name: a_clock
description: "Um aplicativo de relógio digital de tela cheia."
publish_to: 'none'
version: 1.6.0+36
environment:
  sdk: ^3.5.2
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  provider: ^6.1.2
  uuid: ^4.5.1
  flutter_colorpicker: ^1.1.0
  shared_preferences: ^2.1.1
  keep_screen_on: ^4.0.0
  flip_board: ^1.0.0
  url_launcher: ^6.3.1
  google_mobile_ads: ^6.0.0
  flutter_tts: ^4.2.3
  just_audio: ^0.10.4
  firebase_core: ^4.1.1
  firebase_crashlytics: ^5.0.2
  package_info_plus: ^8.3.1
  in_app_purchase: ^3.1.13
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/sounds/
    # Local runtime config (ignored in VCS). The folder is included so that
    # when you create assets/config/admob.json locally it gets bundled.
    - assets/config/
flutter_icons:
  android: true
  image_path: "assets/icon.png"
  adaptive_icon_background: null
  adaptive_icon_foreground: "assets/icon.png"
